version: '3.8'
services:
  neo4j:
    image: neo4j:4.4
    container_name: my_neo4j_4_4
    ports:
      - "7484:7474"
      - "7697:7687"
    environment:
      NEO4J_AUTH: neo4j/12345678 
    volumes:
      - ./plugins:/plugins
      - ./conf:/var/lib/neo4j/conf

  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_gql_app
    ports:
      - "4010:4000"
    depends_on:
      - neo4j
    volumes:
      - .:/app
